######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 9 20:47:54 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += helpFunction.h Point.h solveAlgorithm.h
SOURCES += bruteTest.cpp helpFunction.cpp Point.cpp solveAlgorithm.cpp
