######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 9 20:42:04 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += helpFunction.h Point.h PointPlotterWindow.h solveAlgorithm.h
SOURCES += helpFunction.cpp \
           main.cpp \
           Point.cpp \
           PointPlotter.cpp \
           solveAlgorithm.cpp
